name: Sync Environment Variables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Variables
        run: vercel env pull .env.local --yes --token ${{ secrets.VERCEL_TOKEN }}
        
      - name: Verify Environment Variables
        run: npm run verify-env
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

